baseURL = "/"
contentDir = "content"
layoutDir = "layouts"
publishDir = "docs"
themesDir = "themes"
theme = "paperback"
languageCode = "en-us"
title = "(with poetry)"

[Params]

# your name to display by the copyright sign
# default: undefined
AuthorName = "(wp)"

# tagline to show beneath homepage h1
# default: undefined
Tagline = ""

# number of posts to show on index
# default: 10
HomepagePosts = 5

# default: undefined
# GithubUsername = "damiencaselli"

# default: undefined
# TwitterUsername = "damiencaselli"